---

base_locale: en
locales: [en]

data:
  read:
    - 'config/locales/*.%{locale}.yml'

ignore_missing:
  - layouts.decidim.footer.cc_by_license
  - layouts.decidim.footer.decidim_logo
  - layouts.decidim.footer.made_with_open_source
